server:
  port: 90
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3307/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true